-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 30-11-2020 a las 01:24:10
-- Versión del servidor: 5.7.31
-- Versión de PHP: 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `biblion`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `libros`
--

DROP TABLE IF EXISTS `libros`;
CREATE TABLE IF NOT EXISTS `libros` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `Autor` varchar(255) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `Titulo` varchar(255) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `Editorial` varchar(255) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `Fecha` year(4) NOT NULL,
  `ISBN` varchar(13) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `Genero` varchar(255) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `Descripcion` text CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=213 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Volcado de datos para la tabla `libros`
--

INSERT INTO `libros` (`ID`, `Autor`, `Titulo`, `Editorial`, `Fecha`, `ISBN`, `Genero`, `Descripcion`) VALUES
(64, 'Gianni Rodari', 'Las Aventuras de Pinocho\r\n', 'Ediciones del Laberinto S. L', 1974, '9788484836223', 'Infantiles', 'Este álbum ilustrado es el homenaje que Gianni Rodari quiso hacerle a uno de los personajes más célebres de la literatura mundial. Fiel al texto original y a las secuencias narrativas, Gianni Rodari crea un largo poema rimado en pareados para acercar a los lectores más jóvenes la obra maestra de Carlo Collodi y fascinar con ella a los más grandes.\r\n'),
(49, 'Pablo Álvarez', 'Protocolo Familiar, Naturaleza Jurídica y Eficacia Procesal', 'AKAL', 2020, '9788446048589', 'Académico', ' Este libro analiza la naturaleza jurídica del Protocolo Familiar y enfoca vertientes poco trabajadas en la literatura jurídica como su eficacia procesal y las diferencias y analogías del documento con figuras jurídicas como el trust anglosajón y el fideicomiso latinoamericano.'),
(50, 'Guyton & Hall', 'Compendio de Fisiología Médica 13ED.', 'ELSEVIER', 2016, '9788491130222', 'Académico', 'El principal objetivo del compendio es ofrecer una visión general concisa de los datos y conceptos más importantes del texto del que procede, presentados de un modo que facilite la rápida comprensión de los principios fisiológicos básicos. El índice se corresponde fielmente con el del tratado, y los temas abordados contienen referencias directas a las páginas del texto de referencia, ya que el compendio se actualiza de forma paralela al tratado. '),
(51, 'Norma Ibañez Mancera', 'Propedéutica y Semiología en Odontología', 'ELSEVIER', 2014, '9788490225776', 'Académico', 'Este libro está enfocado y dedicado principalmente a los estudiantes de Odontología, pero también a los profesionales. Facilita al Odontólogo de práctica general o especialista, así como a los estudiantes a diagnosticar presuntivamente padecimientos sistémicos y propios de los tejidos bucales y maxilofaciales, además de identificar los riesgos en la atención odontológica de rutina cuando el paciente esta sistemicamente comprometido.'),
(52, 'DTMS', 'Neurología', 'MARBAN', 2012, '9788471018472', 'Académico', ' En los DTM se desarrollan aspectos de particular interés en la asistencia clínica, como son el diagnóstico diferencial y la evaluación de los principales signos y síntomas, la interpretación de las alteraciones más frecuentemente encontradas en los exámenes complementarios (analítica, radiología), y el adecuado manejo de las enfermedades más prevalentes. La estructura de los capítulos, los convierte en libros donde el lector puede avanzar en función de sus necesidades.'),
(53, 'Thomas Piketty', 'Capital e Ideología', 'GRANO DE SAL', 2019, '9786079870591', 'Académico', 'Desde una perspectiva original en la que confluyen la óptica de la economista y la de quien quiere mejorar la sociedad, el deseo de entreverar múltiples ciencias sociales y de animar el debate público, Thomas Piketty traza en estas páginas la historia y el destino de los regímenes desigualitarios, desde el Antiguo Régimen en Francia hasta el hipercapitalismo de nuestros días y los Estados poscomunistas con sus frívolos magnates.'),
(54, 'Javier Andrés Alonso', 'Redes Privadas Virtuales', 'ALFAOMEGA', 2008, '9786077686668', 'Académico', 'El arma más poderosa que posee el ser humano es la información, ya que le permite conocer, predecir, manipular, sobrevivir y, en definitiva, estar un paso por delante con respecto a quien no dispone de ella. Por esta razón, uno de sus principales objetivos no sólo es llegar a conocer algo, sino tener también la capacidad de salvaguardarlo de forma segura, es decir, que únicamente permanezca accesible para aquellas personas autorizadas.'),
(55, 'Ernesto Ariganello', 'Redes Cisco Guía para la certificación CCNA Security', 'ALFAOMEGA', 2006, '9786077076544', 'Académico', ' La Guía de estudio para la certificación CCNP Routing y Switching proporciona todos los conceptos teórico-prácticos en español, y los comandos y gráficos necesarios para configurar los dispositivos Cisco en redes corporativas. El libro está dividido en tres partes que se fundan cada una en un examen de la certificación profesional de routing y switching.'),
(56, 'Gustavo Galeano', 'Programación de Sistemas Embebidos en C', 'ALFAOMEGA', 2009, '9789586827706', 'Académico', 'Este libro es un gran aliado para la enseñanza de la programación de microcontroladores en lenguaje C, con el cual, alumnos de ingeniería y hasta programadores avanzados, encontrarán sus bases y una gran cantidad de ejemplos prácticos que les permitirán aprender a programar microcontroladores en lenguaje C, con las limitantes de velocidad y consumo propios de estos dispositivos.'),
(57, 'Antonio Hermosa Donate', 'Principios de Electricidad y Electrónica III 2ED.', 'Marcombo', 2007, '9788426716934', 'Académico', 'En este libro se estudian y explican, mediante un enfoque claro y sencillo, los circuitos básicos en corriente alterna (reactancias, impedancia, desfases, factor de potencia, potencias activas y reactivas, resonancia, etc.) así como una introducción al cálculo de circuitos mediante números complejos. Todo ello combinando adecuadamente los conceptos teóricos con la utilidad práctica, y apoyado por diversos ejercicios desarrollados'),
(58, 'Juan Carlos Oros', 'Diseño de Páginas Web C/XHTML, JAVASCRIPT Y CSS 3ED.', 'Alfaomega ', 2013, '9786077071150', 'Académico', 'XHTML es el lenguaje nacido para sustituir al HTML como estándar para la programación de páginas web. Su contenido es de inestimable ayuda tanto para los usuarios que ya saben diseñar páginas Web con HTML (diseñadores, Webmasters, programadores, etc.) como para aquellos que nunca han creado un programa, ya que introduce de manera paulatina y sin esfuerzo el lenguaje JavaScript.'),
(59, 'Arturo Fernandez', 'Python 3 al Descubierto', 'RC Libros', 2009, '9788493945046', 'Académico', 'Python es un lenguaje de programación interpretado, de propósito general y de alto nivel, que en los últimos años ha experimentado un gran auge, gracias a que es fácil de aprender, puede ejecutarse en diferentes sistemas operativos, y además, permite desarrollar aplicaciones rápidamente sin renunciar a un código legible y fácil de mantener.'),
(60, 'Celinda Fournier', 'Estrategias de Ortografía', 'THOMSON/CENGAGE', 2004, '9789706863539', 'Académico', 'El resultado de este trabajo proporciona tanto al profesor como al alumno una guía que facilitará la tarea de ambos; contribuye al logro deobjetivos bien establecidos mediante una variedad de ejercicios. Más que un libro de ortografía es un libro de estrategias de ortografía, pues va más allá de consideraciones teóricas, es decir, puede estudiarse en el aula o de manera autodidacta.'),
(61, 'Daniel Cassany', 'Describir el Escribir', 'PAIDOS', 1989, '9788449326493', 'Académico', 'El escritor, ese viejo desconocido, se sienta a la mesa con papel en blanco. Tiene varias posibilidades y duda: a) Contempla el bucólico paisaje que le rodea. b) Olvida las musas y se apresura a transcribir su pensamiento fugaz; . c) Desconfía de las ideas fáciles y jóvenes; ¿Cuál de estas tres formas de escribir es la normal, la más eficiente, la mejor? ¿Cómo escriben los escritores expertos? ¿Cómo se aprende a escribir?\"'),
(63, 'Giovanni Troconi', 'Diseño Gráfico en México: 100 años', 'ARTES DE MEXICO', 2010, '9786074610406', 'Académico', 'Más de 2,500 imágenes, ocho años de investigación histórica y gráfica llevada a cabo con tenacidad por Giovanni Troconi, un cuerpo sólido y amplio de asesores, una pertinente antología de coautores, permiten ofrecer una visión excepcional del diseño hecho en México durante el siglo XX. Es un libro que ha sido calificado por varios expertos como sugerente, pionero, indispensable, plural, abierto, detonante, un primer paso fundamental.'),
(65, 'Lizardo Carvajal', 'Malaika la princesa 2ED.', 'LuaBooks S.A.S', 2016, '9789585895294', 'Infantiles', 'Malaika es una niña africana, princesa de una manada de elefantes. En el viaje a través de la sabana buscando los bebederos de agua, Malaika entiende que la memoria es la clave de la supervivencia de los elefantes y conoce a los sagrados baobabs. Los días difíciles llegan cuando papá elefante presiente su muerte, entonces Malaika tendrá que enfrentarse a una de las más difíciles pruebas. Malaika la princesa es un libro que abre camino al tema de la muerte como reflexión obligada en la vida.\r\n'),
(66, 'Lizardo Carvajal', 'El pájaro de los mil cantos ', 'LuaBooks S.A.S', 2014, '9789585871403', 'Infantiles', 'Pájaros, trinos, alas y una desbordante imaginación es lo que encontrarán niños y adultos en El pájaro de los mil cantos. Este maravilloso libro ilustrado, te llevará tras el rastro de un misterioso pájaro capaz de imitar a todas las otras aves. En el recorrido descubrirás pájaros nunca antes vistos ni registrados por la ornitología.'),
(67, 'Silvio Rodriguez', 'El hombre extraño', 'LuaBooks S.A.S', 2016, '9789585924321', 'Infantiles', 'El hombre extraño es una de las canciones más entrañables de Silvio Rodríguez y llega ahora a tus manos en forma de libro ilustrado. Este primer libro infantil del cantautor cubano es una mezcla de su reconocida capacidad poética con la creatividad editorial de LuaBooks: un elaborado diseño en forma de acordeón que nos sumerge en la historia de un hombre incomprendido y en el poder transformador del amor.\r\n'),
(68, 'Oliver Jeffers', 'De vuelta a casa', 'Fondo de Cultura Económica', 2019, '9789681685089', 'Infantiles', 'Había una vez un niño que, un día, se quedó atrapado en la luna, y no estaba solo…\r\n'),
(69, 'Oliver Jeffers', 'Perdido y encontrado', 'Fondo de Cultura Económica', 2020, '9789681677596', 'Infantiles', 'Un niño encuentra un pingüino extraviado en la entrada de su casa. Al verlo solo y triste decide ayudarlo a encontrar el camino de regreso a su hogar. Tras mucho investigar, averigua que los pingüinos habitan en el Polo Sur y busca la forma de llevarlo allí. Durante el viaje descubre que la soledad no es lo mismo que la nostalgia del hogar.\r\n'),
(70, 'Drew Daywalt', 'El día en que los crayones renunciaron', 'Fondo de Cultura Económica', 2020, '9786071618122', 'Infantiles', 'Un día, en la escuela, Duncan encontró un montón de cartas para él. Eran sus crayones que, molestos por el trato que recibían, decidieron escribir cartas como ultimátum para Duncan. Crayón Beige está cansado de ser el segundón de Crayón Café; Crayón Negro quiere ser usado para algo más que los contornos; y el Naranja y el Amarillo ya no se hablan por que cada uno cree que es el verdadero color del sol.\r\n'),
(71, 'Dr. Seuss', 'El gato ensombrerado', 'Random House Books for Young Readers', 1957, '9780553509793', 'Infantiles', 'El gato con sombrero cuenta la historia de dos hermanos pequeños que están solos en casa observando aburridos por la ventana, sin nada que hacer, el día lluvioso que acontece al otro lado.\r\n'),
(72, 'Dr. Seuss', 'El Lórax', 'Random House Books for Young Readers', 1971, '9780525707318', 'Infantiles', 'Un muchacho joven, que vive en una ciudad contaminada, visita a un extraño hombre solitario llamado El-Una-Vez. El muchacho le paga a El-Una-Vez quince centavos, un clavo y una concha de mar que pertenecía a su tatarabuelo para que le explique por qué el área está en un estado ruinoso.\r\n'),
(73, 'Mo Willems', '¡No Dejes Que La Paloma Conduzca El Autobús! Edición Illustrated', 'Hyperion Books for Children', 2003, '9781423140528', 'Infantiles', 'El conductor del autobús tiene que salir por un momento, y hace una petición de los lectores: \"No dejen que la paloma conduzca el autobús. \"Hey, puedo conducir el autobús?\", pregunta la paloma. Ante la negativa de los lectores la paloma comienza a rogar e inicia una intensa negociación para conseguir que cambien de opinión.'),
(74, 'Anna Llenas', 'Topito terremoto', 'Beascoa', 2017, '9788448847906', 'Infantiles', 'Anna Llenas, autora dedicada a dar color a la educación emocional, nos presenta este maravilloso álbum. Una historia sobre la hiperactividad y cómo aprender a canalizar esta desbordante y luminosa energía sin prejuicios y desde el amor, para que los más pequeños empiecen a sentirse bien con ellos mismos.\r\n'),
(75, 'Cho Yong', 'El niño que se alimentaba de pesadillas', 'Wisdom House', 2020, '9791190908153', 'Infantiles', 'Es uno de los cinco libros para niños del artista coreano Jamsan relacionados con la exitosa serie de televisión coreana It\'s Okay to Not Be Okay, que se han publicado.\r\n'),
(76, 'Cho Yong', 'Niño Zombie', 'Wisdom House', 2020, '9791190908160', 'Infantiles', 'Es uno de los cinco libros para niños del artista coreano Jamsan relacionados con la exitosa serie de televisión coreana It\'s Okay to Not Be Okay, que se han publicado.\r\n'),
(77, 'Cho Yong', 'El perro alegre', 'Wisdom House', 2020, '9791190908177', 'Infantiles', 'Es uno de los cinco libros para niños del artista coreano Jamsan relacionados con la exitosa serie de televisión coreana It\'s Okay to Not Be Okay, que se han publicado.\r\n'),
(78, 'Cho Yong', 'En busca de la verdadera cara', 'Wisdom House', 2020, '9791190908740', 'Infantiles', 'Es uno de los cinco libros para niños del artista coreano Jamsan relacionados con la exitosa serie de televisión coreana It\'s Okay to Not Be Okay, que se han publicado.\r\n'),
(190, 'ISAAC ASIMOV', 'El Fin de la Eternidad', 'DEBOLSILLO', 2018, '9788497933537', 'Ciencia Ficción', 'En el siglo XXVII, la Tierra funda una organización llamada Eternidad, enviando sus emisarios al pasado y al futuro para abrir el comercio entre las diferentes epocas, y para alterar la larga y a veces trágica historia de la raza humana. El proyecto estaba integrado sólo por los mejores y más brillantes exponentes de cada siglo: personas que dejaron de lado sus propias vidas para dedicarse a servir a los demás.\r\n'),
(189, 'RICHARD MATHESON', 'Soy Leyenda', 'MINOTAURO', 2020, '9788445006764', 'Ciencia Ficción', 'Robert Neville es el único superviviente de una guerra bacteriológica que ha asolado el planeta y convertido al resto de la humanidad en vampiros. Su vida se ha reducido a asesinar el máximo número posible de estos seres sanguinarios durante el día, y a soportar su asedio cada noche. Para ellos, el auténtico monstruo es este hombre que lucha por subsistir en un nuevo orden establecido. \r\n'),
(188, 'RAY BRADBURY', 'El Hombre Ilustrado', 'MINOTAURO', 1901, '9788445077580', 'Ciencia Ficción', 'En esta colección de historias entrelazadas, el narrador anónimo conoce a El Hombre Ilustrado, un curioso personaje con el cuerpo completamente cubierto de tatuajes. Sin embargo, lo más remarcable e inquietante es que las ilustraciones están mágicamente vivas y cada una de ellas empieza a desarrollar su propia historia, como en La pradera donde unos niños llegan un juego de realidad virtual más allá de sus límites.'),
(187, 'ERNEST CLINE', 'Ready Player One', 'S.A. EDICIONES B', 2020, '9788466663069', 'Ciencia Ficción', 'La novela cibernética que ha inspirado la gran producción de Warner Bros, a medio camino entre Avatar y Matrix. Estamos en el año 2044 y, como el resto de la humanidad, Wade Watts prefiere mil veces el videojuego de OASIS al cada vez más sombrío mundo real.\r\n'),
(186, 'H. G. WELLS', 'La Guerra de los Mundos', 'LIBROS DEL ZORRO ROJO', 2016, '9788494570988', 'Ciencia Ficción', 'La guerra de los mundos (1898) narró por primera vez en la historia de la literatura la invasión de la Tierra por extraterrestres procedentes de Marte. En 1906, el artista brasileño Henrique Alvim Corrêa realizó un extraordinario trabajo de ilustración de la novela que recibió la aprobación y admiración del propio H. G. Wells.\r\n'),
(185, 'H. G. WELLS', 'La Máquina del Tiempo', 'SUSAETA', 2019, '9788467766752', 'Ciencia Ficción', 'Esta novela inaugura el tema de los viajes a otras épocas de la historia. En sus páginas, H. G. Wells mezcla el relato de aventuras con la enseñanza social y política. Quiere que tomemos conciencia de nuestra responsabilidad en el devenir de la humanidad.'),
(184, 'ISAAC ASIMOV', 'Yo, Robot', 'EDHASA', 2009, '9788435018364', 'Ciencia Ficción', 'Publicada por primera vez en 1950, cuando la electrónica digital estaba en su infancia, Yo, robot resultó ciertamente visionaria y tendría una influencia enorme no sólo en toda la ciencia ficción posterior, sino incluso en la propia ciencia de la robótica. Aquí formuló Issac Asimov por primera vez las tres leyes fundamentales de la robótica, de las que se valdría para plantear interrogantes que se adentran en el campo de la ética y de la psicología.'),
(182, 'George R. R. Martin', 'Juego de Tronos', 'Penguin Random House Grupo Editorial SA de CV', 2015, '9786073128834', 'Fantasía', 'En el legendario mundo de los Siete Reinos, lord Stark y su familia se encuentran en el centro de un conflicto que desatará todas las pasiones y la más mortal de las batallas.'),
(183, 'ORSON SCOTT CARD', 'El Juego de Ender', 'S.A. EDICIONES B', 2004, '9788466616898', 'Ciencia Ficción', 'La Tierra se ve amenazada por la especia extraterrestre de los insectos, seres que se comunican telepáticamente y que se consideran totalmente distintos de los humanos, a los que quieren destruir. Para vencerles, la humanidad necesita de un genio militar y por ello se permite el nacimiento de Ender que, es el tercer hijo de una pareja en el mundo que ha limitado estrictamente a dos el número de descendientes.\r\n'),
(212, 'ANIELA RODRIGUEZ', 'El Problema de los Tres Cuerpos', 'MINUSCULA', 2019, '9788412092004', 'Ciencia Ficción', 'Estos nueve cuentos de enorme fuerza expresiva recrean la atmósfera viciada propia del presente de México. Lo que aquí se narra podría estar inspirado en cualquiera de las historias de violencia que se suceden a diario en el país. Una humana, íntima fragilidad hermana a los personajes.'),
(211, 'RICK RIORDAN', 'Magos y Semidioses', 'MONTENA', 2017, '9788490437827', 'Ciencia Ficción', 'El mundo está patas arriba cuando Percy Jackson y Annabeth Chase conocen a Carter y Sadie Kane. Están apareciendo criaturas extrañas en lugares inesperados, así que semidioses y magos tienen que unir fuerzas para acabar con todos esos monstruos.\r\n'),
(210, 'STEPHEN W. HAWKING', 'Apocalipsis', 'DEBOLSILLO\r\n', 2018, '9788497599412', 'Ciencia Ficción', 'Un virus gripal, creado artificialmente como posible arma bacteriológica, se extiende por Estados Unidos y el mundo, provocando la muerte de la mayor parte de la población. Los supervivientes tienen sueños comunes, en los que aparece una anciana y un hombre joven. La mujer anciana los incita a viajar a Nebraska para combatir a Randall Flagg, un abominable personaje que lidera las fuerzas del mal y busca la aniquilación definitiva de la humanidad mediante un temible arsenal nuclear. \r\n'),
(209, 'STEPHEN W. HAWKING', 'La Teoría del Todo', 'DEBOLSILLO', 2018, '9788483468913', 'Ciencia Ficción', 'En siete pasos, Hawking logra explicar la historia del universo, desde las primeras teorías del mundo griego y de la época medieval hasta las más complejas teorías actuales, siempre con su característico tono didáctico y accesible a todos los públicos. Newton, Einstein, la mecánica cuántica, los agujeros negros y la teoría de la gran unificación desfilan por estas páginas acercando al lector los misterios del universo.\r\n'),
(208, 'JULIO VERNE', 'Viaje al Centro de la Tierra', 'B DE BOLSILLO', 2008, '9788498721119', 'Ciencia Ficción', 'El profesor y geólogo alemán Otto Liddenbrock viaja al centro de la Tierra desde Islandia, guiado por un escrito de Arne Saknussemm, un sabio islandes del siglo XII. En la peripecia le acompaña su sobrino Axel y también el guía nativo Hans. Los tres personajes entran por un volcán hacia el interior del globo terráqueo donde sufrirán numerosas peripecias'),
(207, 'LISA MAXWELL\r\n', 'El Último Mago ', 'PUCK', 2018, '9788492918072', 'Ciencia Ficción', 'En la Nueva York actual, la magia prácticamente se ha extinguido. Las pocas personas que quedan con afinidad para ella los mageus viven en las sombras, ocultando lo que son. Todo aquel mageus que entra en Manhattan queda atrapado por el Umbral, una barrera de energía oscura que los confina en la isla. Cruzar el Umbral significa perder sus poderes y, a menudo, también la vida. '),
(206, 'NEAL STEPHENSON', 'Snow Crash', 'GIGAMESH', 2000, '9788493066352', 'Ciencia Ficción', 'Snow Crash es una de esas raras novelas que marca un relevo generacional: sus páginas destilan la presencia de una voz innovadora que contempla el mundo con ironía desde una perspectiva tan fresca como radical. Es una obra pirotécnica y vertiginosa, guiada por una incontenible pasión de narrar, pletórica de ideas nuevas y que destila un tono cómplice y socarrón en sus todas sus páginas. \r\n'),
(166, 'Brandon Sanderson', 'El Imperio Final', 'B México', 2016, '9788498726138', 'Fantasía', 'Durante mil años han caído las cenizas y nada florece. Durante mil años los skaa han sido esclavizados y viven sumidos en un miedo inevitable.'),
(167, 'J. R. R. Tolkien', 'El Hobbit', 'ED PLANETA', 2013, '9788445000656', 'Fantasía', 'El hobbit es una novela fantástica del filólogo y escritor británico J. R. R. Tolkien. Fue escrita por partes desde finales de los años 1920 hasta principios de los años 1930 y, en un principio, tan solo tenía el objetivo de divertir a los hijos pequeños de Tolkien.​'),
(168, 'J. R. R. Tolkien', 'El Señor de los Anillos', 'ED PLANETA', 2006, '9788445073728', 'Fantasía', 'Tres Anillos para los Reyes Elfos bajo el cielo.'),
(169, 'Patrick Rothfuss', 'El Nombre del Viento', 'Debolsillo', 2018, '9788499082479', 'Fantasía', 'Esta obra se desarrolla en un mundo fantástico y narra la historia de Kvothe (pronunciado “Cuouz”),3​ arcanista, asesino, enamorado, músico, estudiante y aventurero; y de cómo se convirtió en un personaje legendario. Usando el nombre de Kote para ocultar su verdadera identidad, regenta una apartada posada llamada Roca de Guía, acompañado de su discípulo Bast.'),
(181, 'Peter Bridgewater', 'Introducción al Diseño Gráfico', 'TRILLAS', 1992, '9789682441783', 'Académico', 'Introducción al diseño gráfico es una guía práctica sobre los procedimientos y las técnicas de esta especialidad. Bridgewater orienta de manera clara y concisa acerca de las funciones y el uso del material y el equipo requeridos por el diseñador. Mediante atractivas ilustraciones, a todo color, el autor muestra los métodos de trabajo del diseñador gráfico y penetra en esta actividad para proporcionar al estudiante y a quienes se inician en ella.'),
(171, 'Patrick Rothfuss', 'El Temor de un Hombre Sabio', 'Debolsillo', 2018, '9788499899619', 'Fantasía', '«Todo hombre sabio teme tres cosas: la tormenta en el mar, la noche sin luna y la ira de un hombre amable.»\r\nEl hombre había desaparecido. El mito no. Músico, mendigo, ladrón, estudiante, mago, trotamundos, héroe y asesino, Kvothe había borrado su rastro. Y ni siquiera ahora que le han encontrado, ni siquiera ni siquiera ahora que le han encontrado, ni siquiera ahora que las tinieblas invaden los rincones del mundo, está dispuesto a regresar. '),
(172, ' Andrzej Sapkowski', 'El Último Deseo 9ED.', 'Alamut', 2020, '9788498891270', 'Fantasía', 'Esta antología consta de siete (7) cuentos. Geralt de Rivia, tras ser herido en su lucha con la Estrige de Wizima, descansa en un templo. Durante ese lapso tiene recuerdos de eventos recientes de su vida, cada uno formando una historia en si. En cada uno de esos cuentos se puede ver una reinvención de varios cuentos clásicos como \"la bella y la bestia\" en \"La Semilla de la Verdad\" o \"Blancanieves y los siete enanitos\" en \"Un mal menor\".'),
(173, 'Joe Abercrombie', 'La Voz de las Espadas', ' Alianza', 2009, '9788420679877', 'Fantasía', 'El inquisidor Glokta, convertido en un cínico tullido tras su paso por las cárceles de los enemigos de la Unión, es ahora a su vez un eficaz torturador capaz de extraer información de cualquiera.'),
(174, 'Andrzej Sapkowski', 'La Espada del Destino', 'Artifex ', 2018, '9788498891058', 'Fantasía', 'La vida de un brujo cazador de monstruos no es fácil. Tan pronto puede uno tener que meterse hasta el cuello en un estercolero para eliminar a la bestia carroñera que amenaza a la ciudad, intentando no atrapar una infección incurable, como se puede encontrar unido a la cacería de uno de los últimos dragones, en la que la cuestión no es si los cazadores conseguirán matar a la pobre bestia.'),
(175, 'Brandon Sanderson', 'El Pozo de la Ascensión', 'S.A. EDICIONES B', 2012, '9788466658904', 'Fantasía', 'El Pozo de la Ascensión es el segundo volumen de la saga «Nacidos de la Bruma [Mistborn]», una obra iniciada con El imperio final y parte imprescindible del Cosmere, el universo destinado a dar forma a la serie más extensa y fascinante jamás escrita en el ámbito de la fantasía épica.'),
(176, 'Brandon Sanderson', 'El Camino de los Reyes', 'NOVA', 2011, '765365278', 'Fantasía', 'Anhelo los días previos a la última Desolación. Los días en que los Heraldos nos abandonaron y los Caballeros Radiantes se giraron en nuestra contra. Un tiempo en que aún había magia en el mundo y honor en el corazón de los hombres. El mundo fue nuestro, pero lo perdimos.'),
(177, 'Steven Erikson', 'Los Jardines de la Luna', 'NOVA', 2017, '9788466660877', 'Fantasía', 'Tras interminables guerras, amargas luchas internas y sangrientas confrontaciones, incluso las tropas imperiales necesitan un descanso. Pero la obsesión expansionista de la emperatriz Lassen no tiene límites, y cuenta con el apoyo de sus sanguinarios agentes de la Garra. Tras el último asedio, el sargento Whiskeyjack y su pelotón de Abrasapuentes necesitan tiempo para descansar y enterrar a sus muerto.'),
(178, 'Andrzej Sapkowski', 'La Sangre de los Elfos', 'Océano', 2018, '9788498891065', 'Fantasía', '\"En verdad les digo que se acerca el tiempo de la espada y el hacha, la época de la tormenta salvaje. Se acerca el Tiempo del Invierno Blanco y de la Luz Blanca, el Tiempo de la Locura y el Tiempo del Odio, el Tiempo del Fin. El mundo morirá entre la escarcha y resucitará de nuevo junto con el nuevo sol. Resucitará de entre la Antigua Sangre, de Hen Ichaer, de la semilla sembrada. De la semilla que no germina sino que estalla en llamas\".'),
(179, 'Neil Gaiman', 'American Gods 10ED.', 'William Morrow', 2016, '9780062472106', 'Fantasía', 'Días antes de salir de prisión, la mujer de Sombra, Laura, muere en un misterioso accidente de coche. Aturdido por el dolor, emprende el regreso a casa. En el avión, se encontrará con el enigmático señor Miércoles, que dice ser un refugiado de una guerra antigua, un dios y también el rey de América.'),
(180, 'Terry Pratchett', 'El Color de la Magia 6ED.', 'Debolsillo', 2006, '9788497596794', 'Fantasía', 'Primer volumen de la serie Mundodisco de Terry Pratchett En un mundo plano sostenido por cuatro elefantes impasibles -que se apoyan en la espalda de una tortuga gigante- habitan los estrafalarios personajes de esta novela: un hechicero avaro y torpe.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuarios`
--

DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `ID` int(12) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(255) COLLATE utf8_spanish_ci NOT NULL,
  `Apellido` varchar(255) COLLATE utf8_spanish_ci NOT NULL,
  `Correo` varchar(255) COLLATE utf8_spanish_ci NOT NULL,
  `Sexo` varchar(255) COLLATE utf8_spanish_ci NOT NULL,
  `Password` varchar(255) COLLATE utf8_spanish_ci NOT NULL,
  `Nivel` varchar(13) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'Usuario',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;

--
-- Volcado de datos para la tabla `usuarios`
--

INSERT INTO `usuarios` (`ID`, `Nombre`, `Apellido`, `Correo`, `Sexo`, `Password`, `Nivel`) VALUES
(1, 'fygtjuhdrtf', 'dgfhjfghj', 'sdfrhgsd@gmail.com', 'Femenino', 'Paco', 'Usuario'),
(2, 'Jacob', 'Díaz', 'jacob.diaz@alumnos.udg.mx', 'Maculino', 'Paco', 'Administrador'),
(10, 'usuario', 'apellido', 'uncorreo@hotmail.com', 'Femenino', 'ContraseÃ±a', 'Usuario'),
(9, 'sdf', 'dsf', 'correo@gmail.com', 'Femenino', 'qwert', 'Administrador'),
(11, 'fhgujf', 'fghjfg', 'hjfghj@gmail.com', 'Femenino', '1234', 'Usuario'),
(12, 'sdfg', 'sdfg', 'sdfg@gmail.com', 'Femenino', 'asdfsad', 'Usuario'),
(13, 'sdfgsdf', 'sdfgsdf', 'sdfg@gmail.com', 'Femenino', 'sdfg', 'Usuario'),
(14, 'UnNombre', 'UnApellido', 'correodeprueba@outlook.com', 'Masculino', 'ContraseÃ±a', 'Administrador');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
